#!/bin/bash

set -e

go get -u github.com/Songmu/goxz/cmd/goxz
go get -u github.com/tcnksm/ghr

latest_tag="$(git describe --abbrev=0 --tags)"
goxz -d dist/$latest_tag -z -os darwin,linux -arch amd64,386
ghr -u aereal -r go-http-magi $latest_tag dist/$latest_tag
